### ISSUE TITLE
Changing the background image

### ISSUE THREAD

**Issue by millernj** [mlfiii/Week7Project1#24]
Let's use one of the duplicating ones on [here](https://www.toptal.com/designers/subtlepatterns/)

**Comment by mlfiii** [comment]
We discussed today that really the website should look more congruent with other news agency websites such as google news, msnbc or cnn.  This would mean a basic white background with pleasant colors.

**Comment by mlfiii** [comment]
I commented out the background image and made the background-color smokeywhite to give it a bit of contrast with the card.  I also made changes to layout so that the search input box is closer to search button.
