### ISSUE TITLE
Cleaning up the ui

### ISSUE THREAD

**Issue by millernj** [mlfiii/Week7Project1#28]
Let's clean up how the website looks.

**Comment by mlfiii** [comment]
Cleaned-up UI a bit.  Created fixed header and placed the search box and button inside.  Reduced the amount of unused space between search box and top articles.
![image](https://user-images.githubusercontent.com/57580332/74676743-8ef51b80-516b-11ea-9c36-680c3001b794.png)
![image](https://user-images.githubusercontent.com/57580332/74676753-94526600-516b-11ea-8542-454950e37899.png)
