### ISSUE TITLE
Design basic layout.

### ISSUE THREAD

**Issue by millernj** [mlfiii/Week7Project1#4]
As a user, when I visit the home page, top stories populate the view.

As a user, when I visit the home page, I will see a text box that will allows me to input a string of text used to query the API.

As a user, when I visit the page, each headline has a button that allows me to save headline, make synopsis', and get sentiment.

As a user, I’d like to see an icon next to the headline that indicates the publisher of the article.
Create user stories:

As a news reader, I want to see top headlines of the day immediately so that even if I have something I want to lookup, I don’t want to miss anything important from that day.

As a user, when I visit the home page, top stories populate the view.

As a user, when I visit the home page, I will see a text box that will allows me to input a string of text used to query the API.

As a user, when I visit the page, each headline has a button that allows me to save headline.  

As a user, I’d like to see an icon next to the headline that indicates the publisher of the article.

**Comment by millernj** [comment]
check this out: https://instabug.com/blog/mobile-app-design-tools/

**Comment by mlfiii** [comment]
![image](https://user-images.githubusercontent.com/57580332/74092582-f11e9400-4a7a-11ea-86bd-ab3614790b56.png)

**Comment by mlfiii** [comment]
Worked on basic layout.  Removed "News" image and replaced with "The News Stand" text.  Moved some of the objects around.  The concept being that the cards are hanging off of the objects above them much like a sign would.  The objects above cascade to the right towards the center where the cards hang.

![image](https://user-images.githubusercontent.com/57580332/74626165-b1534e80-5103-11ea-8f51-72c0d5c906bf.png)
![image](https://user-images.githubusercontent.com/57580332/74626174-badcb680-5103-11ea-822b-25ea8c6e08b6.png)
